### PR TITLE
Fix media progress bar on android 10

### LINKED ISSUE #2: Pausing resets system music progress bar (Android 10+)
First of all I'm very impressed by your work! It shows so much potential. Now, I'm sure you might be already aware of this issue, but I'll submit it nonetheless.

**Description :**
As the title states, pausing a music in Gelli resets the system music progress bar (it goes back to 00:00, and I can't get it to "resync" unless I play another song).

**Versions impacted** : 0.8.0, master (45d4cb84b04ef746f2a6709291d0a16d971079e1)

**Android version** : 10

**Screenshots** :
[Pausing](https://user-images.githubusercontent.com/5507232/83802967-ff3c9400-a6ab-11ea-9b14-d45d96b3d2af.png)
[After pausing](https://user-images.githubusercontent.com/5507232/83802959-fba90d00-a6ab-11ea-96d7-18abbe09f8eb.png)

Hope it helps!

### PR DESCRIPTION
**Pull request by KristupasSavickas**
Fixes the following issues with the media progress bar on Android 10:
- When a song ends the progress would persist on the next one
- Seeking using the progress bar doesn't work
- Pausing resets the progress bar to 0

Closes #2

### CODE REVIEW

**Comment by KristupasSavickas** [comment]
Note that I don't know what the fuck I'm doing, this is the first time I ever installed Android Studio, but this is so much better compared to the official client that I'm willing to bash my head against the wall to improve it even more.

File: app/src/main/java/com/dkanada/gramophone/service/MusicService.java [hunk 1]
```diff
@@ -1301,25 +1303,4 @@ public void run() {
             handleAndSendChangeInternal(MEDIA_STORE_CHANGED);
         }
     }
-
-    private class ThrottledSeekHandler implements Runnable {
```
Comment (KristupasSavickas) [inline app/src/main/java/com/dkanada/gramophone/service/MusicService.java:1305]: Not really sure why this was needed...

Comment (dkanada) [reply app/src/main/java/com/dkanada/gramophone/service/MusicService.java:1305]: My guess is that every single change will trigger the intent, which will get processed by an arbitrary number of classes. That might cause older phones or maybe even current phones to run into performance issues but I'd have to test it out first.

**Comment by dkanada** [comment]
I just updated my phone so I can actually test this pull request now. Sorry for taking so long to get this one merged, definitely improves the new notification.

**Comment by dkanada** [comment]
I've been looking at this one again, the ThrottledSeekHandler is definitely required to avoid spamming events (this could cause lag on older devices) so now I just need to confirm all the events are as efficient as possible.
