### PR TITLE
Fix favorites shuffle button

### LINKED ISSUE #150: Random playing favorites does not work anymore
Instead, Gelli random plays the whole library. It was not the case before 1.3.0.

### LINKED ISSUE #179: Shuffle all on favorites doesn't shuffle favorites
There are 2 shuffle all buttons in Gelli, one on the "Songs" page, which shuffles the whole library as expected but there's another one in "Favorites" which does not shuffle just the favorites but also the whole library.

It would be nice if it would be possible to shuffle only the favorites this way.

### PR DESCRIPTION
**Pull request by jakobkukla**
Fixes #150, fixes #179.

Probably not the cleanest solution.

### CODE REVIEW

File: app/src/main/java/com/dkanada/gramophone/adapter/song/ShuffleButtonSongAdapter.java [hunk 1]
```diff
@@ -65,6 +67,10 @@ public void onBindViewHolder(@NonNull final SongAdapter.ViewHolder holder, int p
         }
     }
 
+    public void setFavorite(boolean favorite) {
+        onlyFavorites = favorite;
```
Comment (dkanada) [inline app/src/main/java/com/dkanada/gramophone/adapter/song/ShuffleButtonSongAdapter.java:71]: Can we match the variable name with the setter name? Either `favorite` on the private variable or `favorites` for both sounds fine.

File: app/src/main/java/com/dkanada/gramophone/util/ShortcutUtil.java [hunk 2]
```diff
@@ -34,12 +35,16 @@ public static void getLatest(MediaCallback<Song> callback) {
         getSongs(query, callback);
     }
 
-    public static void getShuffle(MediaCallback<Song> callback) {
+    public static void getShuffle(MediaCallback<Song> callback, boolean onlyFavorites) {
```
Comment (dkanada) [inline app/src/main/java/com/dkanada/gramophone/util/ShortcutUtil.java:38]: this one is technically different too

**Comment by dkanada** [comment]
@jakobkukla totally forgot about this pull request, apologies. I'll get it into a release with the other two next weekend.
