### PR TITLE
Fixed app crash when trying to connect without server address

### LINKED ISSUE #17: The app closes when you leave all empty fields at login
When trying to login with all fields empty, the app closes

- Phone: Pocophone
- Android: 10
- MIUI: 11

### PR DESCRIPTION
**Pull request by ThibaultNocchi**
Currently, clicking by mistake (or not haha) the login button while the server field is empty simply crashes the app. A simple try / catch around the login method with the display of a toast does the trick.

Fixes #17

### CODE REVIEW

File: app/src/main/java/com/dkanada/gramophone/ui/activities/LoginActivity.java [hunk 1]
```diff
@@ -122,6 +128,8 @@ public void onResponse(AuthenticationResult result) {
                     });
                 }
             });
+
+
```
Comment (dkanada) [inline app/src/main/java/com/dkanada/gramophone/ui/activities/LoginActivity.java:132]: Could you remove these lines?

Comment (ThibaultNocchi) [reply app/src/main/java/com/dkanada/gramophone/ui/activities/LoginActivity.java]: It's done! :)
